# Generated by Django 5.0.6 on 2024-07-18 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appraiser',
            name='status_appraiser',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended')], default='active', max_length=50),
        ),
        migrations.AlterField(
            model_name='asset',
            name='property_status',
            field=models.CharField(choices=[('available', 'Available'), ('sold', 'Sold'), ('reserved', 'Reserved')], default='available', max_length=50),
        ),
        migrations.AlterField(
            model_name='asset',
            name='status_asset',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('pending', 'Pending'), ('sold', 'Sold')], default='active', max_length=50),
        ),
        migrations.AlterField(
            model_name='assetmedia',
            name='type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('document', 'Document')], max_length=50),
        ),
    ]
