# Generated by Django 5.0.6 on 2024-07-24 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_alter_appraiser_status_appraiser_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assetmedia',
            name='description',
        ),
        migrations.RemoveField(
            model_name='assetmedia',
            name='link',
        ),
        migrations.RemoveField(
            model_name='assetmedia',
            name='type',
        ),
        migrations.AddField(
            model_name='assetmedia',
            name='media_file',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
    ]
