# Generated by Django 5.0.6 on 2024-07-23 12:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_alter_appraiser_status_appraiser_and_more'),
        ('auctions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='auctionhasasset',
            old_name='present_price',
            new_name='current_price',
        ),
        migrations.RemoveField(
            model_name='auction',
            name='id_holiday',
        ),
        migrations.RemoveField(
            model_name='auctionhasasset',
            name='auction_result',
        ),
        migrations.AddField(
            model_name='auction',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='auctionhasasset',
            name='final_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='auctionhasasset',
            name='id_asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_auctions', to='assets.asset'),
        ),
        migrations.AlterField(
            model_name='auctionhasasset',
            name='id_auction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auction_assets', to='auctions.auction'),
        ),
        migrations.AlterField(
            model_name='auctionhasasset',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('finished', 'Finished'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='bid',
            name='bid_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='bid',
            name='id_auction_has_asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='auctions.auctionhasasset'),
        ),
        migrations.AlterField(
            model_name='bid',
            name='id_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='contract',
            name='id_auction_has_asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='auctions.auctionhasasset'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='id_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='contract',
            name='status_contract',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('finished', 'Finished'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='fee',
            name='id_auction_has_asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fees', to='auctions.auctionhasasset'),
        ),
        migrations.AlterField(
            model_name='taxhascontract',
            name='id_contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taxes', to='auctions.contract'),
        ),
        migrations.AlterField(
            model_name='taxhascontract',
            name='id_tax',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_taxes', to='auctions.tax'),
        ),
        migrations.AlterField(
            model_name='userhasauction',
            name='id_auction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='auctions.auction'),
        ),
        migrations.AlterField(
            model_name='userhasauction',
            name='id_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='joined_auctions', to=settings.AUTH_USER_MODEL),
        ),
    ]
