# Generated by Django 5.0.6 on 2024-07-18 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_notification_alter_user_email_alter_user_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='informationaccount',
            name='status',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='status',
        ),
        migrations.RemoveField(
            model_name='transactionhistory',
            name='status',
        ),
    ]
